[package]
name = "possiblepanda/queryauth"
description = "A fully type-safe permissions module for Roblox Luau."
license = "MIT"
authors = ["Possible Panda"]
version = "1.0.1"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["default.project.json", "lib", "lib/**", "LICENSE.txt", "wally.toml"]
private = false